import { useEffect, useRef, useState } from "react";
import { pairWeb, remoteCommand, remoteState, type WebCredential } from "./remoteTransport";

const SESSION_KEY = "djgoo-web-session";
const REMEMBER_KEY = "djgoo-web-remembered";
export function RemoteApp({ invite }: { invite: string }) {
  const [credential, setCredential] = useState<WebCredential | null>(() => JSON.parse(sessionStorage.getItem(SESSION_KEY) || localStorage.getItem(REMEMBER_KEY) || "null"));
  const [state, setState] = useState<any>(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [remember, setRemember] = useState(false);
  const refreshing = useRef(false);
  async function refresh() { if (!credential || refreshing.current) return; refreshing.current = true; try { setState(await remoteState(credential)); setError(""); } catch (e) { setError(String((e as Error).message)); } finally { refreshing.current = false; } }
  useEffect(() => { if (!credential) return; void refresh(); let timer = 0; const schedule = () => { clearInterval(timer); if (!document.hidden) timer = window.setInterval(refresh, 15000); }; document.addEventListener("visibilitychange", schedule); schedule(); return () => { clearInterval(timer); document.removeEventListener("visibilitychange", schedule); }; }, [credential]);
  async function connect() { try { const paired = await pairWeb(invite, navigator.userAgent.includes("Mobile") ? "DjGoo Web Mobile" : "DjGoo Web Browser"); setCredential(paired.credential); sessionStorage.setItem(SESSION_KEY, JSON.stringify(paired.credential)); if (remember) localStorage.setItem(REMEMBER_KEY, JSON.stringify(paired.credential)); } catch (e) { setError(String((e as Error).message)); } }
  async function command(intent: string, values: Record<string, unknown> = {}) { if (!credential) return; try { await remoteCommand(credential, intent, values); await refresh(); } catch (e) { setError(String((e as Error).message)); } }
  if (!credential) return <main className="remote-shell"><section className="remote-pair"><img src="./djgoo-mark.svg" alt=""/><h1>Pair with DjGoo</h1><p>This private invitation connects your browser to the Discord music session.</p><label><input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)}/> Remember this device</label><button onClick={connect}>Connect securely</button>{error && <p className="error">{error}</p>}</section></main>;
  return <main className="remote-shell"><header><img src="./djgoo-mark.svg" alt=""/><div><strong>DjGoo Web</strong><small>Discord member controls</small></div><button onClick={refresh}>Refresh</button></header>{error && <div className="banner error">{error}</div>}<section className="remote-now"><span>{state?.playback?.state || "Connecting"}</span><h1>{state?.playback?.title || "Nothing playing"}</h1><p>{state?.playback?.artist || state?.playback?.station || ""}</p></section><section className="remote-controls"><button onClick={() => command("pause")}>Pause</button><button onClick={() => command("resume")}>Resume</button><button onClick={() => command("skip")}>Vote skip</button><button onClick={() => command("station_like_current")}>Like</button><button onClick={() => command("station_less_like_current")}>Less like</button></section><form className="remote-search" onSubmit={e => { e.preventDefault(); if (query.trim()) void command("play", { query: query.trim(), raw: query.trim() }); }}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Request a song" maxLength={500}/><button>Play</button></form><section className="remote-queue"><h2>Queue</h2>{(state?.queue || []).map((track: any) => <div key={track.id || track.title}><strong>{track.title}</strong><span>{track.artist || track.requester || ""}</span></div>)}</section></main>;
}
