from __future__ import annotations

from tools.update_apply_engine import (
    PARENT_EXIT_TIMEOUT_SECONDS,
    REPLACE_TIMEOUT_SECONDS,
    ROLLBACK_TIMEOUT_SECONDS,
    UpdateApplyError,
    _atomic_copy,
    _atomic_remove,
    _cleanup_staging,
    _terminate_windows_pids,
    _wait_for_windows_process,
    _windows_pids_for_executable,
    _write_json,
    apply_staged_update,
    extract_verified_bundle,
    invoke_stack,
    load_manifest,
    main,
    manifest_deletes,
    manifest_files,
    recorded_supervisor_pid,
    restart_launcher,
    run_update,
    safe_relative_path,
    sha256_file,
    stack_was_running,
    validate_bundle,
    wait_for_executable_release,
    wait_for_process_exit,
)


__all__ = [
    "PARENT_EXIT_TIMEOUT_SECONDS",
    "REPLACE_TIMEOUT_SECONDS",
    "ROLLBACK_TIMEOUT_SECONDS",
    "UpdateApplyError",
    "_atomic_copy",
    "_atomic_remove",
    "_cleanup_staging",
    "_terminate_windows_pids",
    "_wait_for_windows_process",
    "_windows_pids_for_executable",
    "_write_json",
    "apply_staged_update",
    "extract_verified_bundle",
    "invoke_stack",
    "load_manifest",
    "main",
    "manifest_deletes",
    "manifest_files",
    "recorded_supervisor_pid",
    "restart_launcher",
    "run_update",
    "safe_relative_path",
    "sha256_file",
    "stack_was_running",
    "validate_bundle",
    "wait_for_executable_release",
    "wait_for_process_exit",
]


if __name__ == "__main__":
    raise SystemExit(main())
